In [1]:
import pandas as pd

In [2]:
fifa = pd.read_csv('fifa21_raw_data.csv',nrows=5)

In [3]:
print(fifa.columns)

Index(['photoUrl', 'LongName', 'playerUrl', 'Nationality', 'Positions', 'Name',
       'Age', '↓OVA', 'POT', 'Team & Contract', 'ID', 'Height', 'Weight',
       'foot', 'BOV', 'BP', 'Growth', 'Joined', 'Loan Date End', 'Value',
       'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [4]:
fifa

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,273

In [5]:
fifa = pd.read_csv('fifa21_raw_data.csv',dtype={76: str})

In [6]:
fifa

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,...,Low,Low,1 ★,58,23,26,27,50,48,\n2
18975,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,70,46,40,53,16,40,\n3
18976,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,...,Medium,Medium,1 ★,64,28,26,38,48,51,\n3
18977,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,64,40,48,49,35,45,\n5
18978,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,...,Medium,Medium,1 ★,57,32,43,48,44,49,\n2

In [7]:
fifa1=fifa.copy()

In [8]:
fifa

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,...,Low,Low,1 ★,58,23,26,27,50,48,\n2
18975,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,70,46,40,53,16,40,\n3
18976,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,...,Medium,Medium,1 ★,64,28,26,38,48,51,\n3
18977,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,64,40,48,49,35,45,\n5
18978,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,...,Medium,Medium,1 ★,57,32,43,48,44,49,\n2

In [9]:
fifa.columns

Index(['photoUrl', 'LongName', 'playerUrl', 'Nationality', 'Positions', 'Name',
       'Age', '↓OVA', 'POT', 'Team & Contract', 'ID', 'Height', 'Weight',
       'foot', 'BOV', 'BP', 'Growth', 'Joined', 'Loan Date End', 'Value',
       'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [10]:
fifa.drop(['photoUrl','LongName','playerUrl'], inplace = True, axis = 1)

In [11]:
fifa

,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,ID,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,"5'7""",159lbs,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,"6'2""",183lbs,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,"6'2""",192lbs,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,"5'11""",154lbs,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,"5'9""",150lbs,...,High,Medium,5 ★,91,85,86,94,36,59,\n273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,257710,"5'10""",154lbs,...,Low,Low,1 ★,58,23,26,27,50,48,\n2
18975,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258736,"5'7""",128lbs,...,Medium,Medium,1 ★,70,46,40,53,16,40,\n3
18976,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,247223,"5'10""",146lbs,...,Medium,Medium,1 ★,64,28,26,38,48,51,\n3
18977,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258760,"5'9""",143lbs,...,Medium,Medium,1 ★,64,40,48,49,35,45,\n5
18978,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,255958,"5'9""",150lbs,...,Medium,Medium,1 ★,57,32,43,48,44,49,\n2

In [12]:
fifa = fifa.rename({'↓OVA' : 'OVA'}, axis = 1)

In [13]:
fifa

,Nationality,Positions,Name,Age,OVA,POT,Team & Contract,ID,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,"5'7""",159lbs,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,"6'2""",183lbs,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,"6'2""",192lbs,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,"5'11""",154lbs,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,"5'9""",150lbs,...,High,Medium,5 ★,91,85,86,94,36,59,\n273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,257710,"5'10""",154lbs,...,Low,Low,1 ★,58,23,26,27,50,48,\n2
18975,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258736,"5'7""",128lbs,...,Medium,Medium,1 ★,70,46,40,53,16,40,\n3
18976,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,247223,"5'10""",146lbs,...,Medium,Medium,1 ★,64,28,26,38,48,51,\n3
18977,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,258760,"5'9""",143lbs,...,Medium,Medium,1 ★,64,40,48,49,35,45,\n5
18978,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,255958,"5'9""",150lbs,...,Medium,Medium,1 ★,57,32,43,48,44,49,\n2

In [14]:
fifa['Team & Contract'] = fifa['Team & Contract'].str.strip("\r\n\r\n\r\n\r\n")

In [15]:
fifa

,Nationality,Positions,Name,Age,OVA,POT,Team & Contract,ID,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,Argentina,RW ST CF,L. Messi,33,93,93,FC Barcelona\n2004 ~ 2021,158023,"5'7""",159lbs,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,Juventus\n2018 ~ 2022,20801,"6'2""",183lbs,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,Slovenia,GK,J. Oblak,27,91,93,Atlético Madrid\n2014 ~ 2023,200389,"6'2""",192lbs,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,Belgium,CAM CM,K. De Bruyne,29,91,91,Manchester City\n2015 ~ 2023,192985,"5'11""",154lbs,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,Brazil,LW CAM,Neymar Jr,28,91,91,Paris Saint-Germain\n2017 ~ 2022,190871,"5'9""",150lbs,...,High,Medium,5 ★,91,85,86,94,36,59,\n273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,Chongqing Dangdai Lifan FC SWM Team\n2020 ~ 2020,257710,"5'10""",154lbs,...,Low,Low,1 ★,58,23,26,27,50,48,\n2
18975,England,ST,V. Da Silva,17,47,67,Oldham Athletic\n2020 ~ 2021,258736,"5'7""",128lbs,...,Medium,Medium,1 ★,70,46,40,53,16,40,\n3
18976,China PR,CB,Xia Ao,21,47,55,Wuhan Zall\n2018 ~ 2022,247223,"5'10""",146lbs,...,Medium,Medium,1 ★,64,28,26,38,48,51,\n3
18977,England,CM,B. Hough,17,47,67,Oldham Athletic\n2020 ~ 2021,258760,"5'9""",143lbs,...,Medium,Medium,1 ★,64,40,48,49,35,45,\n5
18978,Bolivia,CDM,M. Flores,19,47,63,Club Bolívar\n2020 ~ 2024,255958,"5'9""",150lbs,...,Medium,Medium,1 ★,57,32,43,48,44,49,\n2

In [16]:
fifa.duplicated().sum

<bound method Series.sum of 0        False
1        False
2        False
3        False
4        False
         ...
18974    False
18975    False
18976    False
18977    False
18978    False
Length: 18979, dtype: bool>

In [17]:
# Extracting team information from 'Team & Contract' column
fifa['Team'] = fifa['Team & Contract'].str.split('\n').str[1].str.strip()

# Extracting contract details (assuming contract information is contained in numbers and the tilde symbol)
fifa['Contract'] = fifa['Team & Contract'].str.extract(r'(\d{4}~?\d{4}|\d{4})')

# Extracting contract start year
fifa['Contract_start'] = fifa['Contract'].str.split('~').str[0].astype(int, errors='ignore')

# Extracting contract end year
fifa['Contract_end'] = fifa['Contract'].str.split('~').str[-1].astype(int, errors='ignore')

# Converting start and end contract years to numeric, handling errors with 'coerce' and filling missing values with 0
fifa['Contract_start'] = pd.to_numeric(fifa['Contract_start'], errors="coerce").fillna(0).astype(int)
fifa['Contract_end'] = pd.to_numeric(fifa['Contract_end'], errors="coerce").fillna(0).astype(int)

In [18]:
fifa['Teams'] = fifa['Team & Contract'].str.replace(r'\n.*', '', regex = True)

In [19]:
fifa

,Nationality,Positions,Name,Age,OVA,POT,Team & Contract,ID,Height,Weight,...,PAS,DRI,DEF,PHY,Hits,Team,Contract,Contract_start,Contract_end,Teams
0,Argentina,RW ST CF,L. Messi,33,93,93,FC Barcelona\n2004 ~ 2021,158023,"5'7""",159lbs,...,91,95,38,65,\n372,2004 ~ 2021,2004,2004,2004,FC Barcelona
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,Juventus\n2018 ~ 2022,20801,"6'2""",183lbs,...,81,89,35,77,\n344,2018 ~ 2022,2018,2018,2018,Juventus
2,Slovenia,GK,J. Oblak,27,91,93,Atlético Madrid\n2014 ~ 2023,200389,"6'2""",192lbs,...,78,90,52,90,\n86,2014 ~ 2023,2014,2014,2014,Atlético Madrid
3,Belgium,CAM CM,K. De Bruyne,29,91,91,Manchester City\n2015 ~ 2023,192985,"5'11""",154lbs,...,93,88,64,78,\n163,2015 ~ 2023,2015,2015,2015,Manchester City
4,Brazil,LW CAM,Neymar Jr,28,91,91,Paris Saint-Germain\n2017 ~ 2022,190871,"5'9""",150lbs,...,86,94,36,59,\n273,2017 ~ 2022,2017,2017,2017,Paris Saint-Germain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,Chongqing Dangdai Lifan FC SWM Team\n2020 ~ 2020,257710,"5'10""",154lbs,...,26,27,50,48,\n2,2020 ~ 2020,2020,2020,2020,Chongqing Dangdai Lifan FC SWM Team
18975,England,ST,V. Da Silva,17,47,67,Oldham Athletic\n2020 ~ 2021,258736,"5'7""",128lbs,...,40,53,16,40,\n3,2020 ~ 2021,2020,2020,2020,Oldham Athletic
18976,China PR,CB,Xia Ao,21,47,55,Wuhan Zall\n2018 ~ 2022,247223,"5'10""",146lbs,...,26,38,48,51,\n3,2018 ~ 2022,2018,2018,2018,Wuhan Zall
18977,England,CM,B. Hough,17,47,67,Oldham Athletic\n2020 ~ 2021,258760,"5'9""",143lbs,...,48,49,35,45,\n5,2020 ~ 2021,2020,2020,2020,Oldham Athletic
18978,Bolivia,CDM,M. Flores,19,47,63,Club Bolívar\n2020 ~ 2024,255958,"5'9""",150lbs,...,43,48,44,49,\n2,2020 ~ 2024,2020,2020,2020,Club Bolívar

In [20]:
fifa.drop(['Team & Contract','Team','Contract'], inplace = True, axis =1)

In [21]:
fifa

,Nationality,Positions,Name,Age,OVA,POT,ID,Height,Weight,foot,...,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Contract_start,Contract_end,Teams
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,"5'7""",159lbs,Left,...,85,92,91,95,38,65,\n372,2004,2004,FC Barcelona
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,"6'2""",183lbs,Right,...,89,93,81,89,35,77,\n344,2018,2018,Juventus
2,Slovenia,GK,J. Oblak,27,91,93,200389,"6'2""",192lbs,Right,...,87,92,78,90,52,90,\n86,2014,2014,Atlético Madrid
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,"5'11""",154lbs,Right,...,76,86,93,88,64,78,\n163,2015,2015,Manchester City
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,"5'9""",150lbs,Right,...,91,85,86,94,36,59,\n273,2017,2017,Paris Saint-Germain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,"5'10""",154lbs,Right,...,58,23,26,27,50,48,\n2,2020,2020,Chongqing Dangdai Lifan FC SWM Team
18975,England,ST,V. Da Silva,17,47,67,258736,"5'7""",128lbs,Right,...,70,46,40,53,16,40,\n3,2020,2020,Oldham Athletic
18976,China PR,CB,Xia Ao,21,47,55,247223,"5'10""",146lbs,Right,...,64,28,26,38,48,51,\n3,2018,2018,Wuhan Zall
18977,England,CM,B. Hough,17,47,67,258760,"5'9""",143lbs,Right,...,64,40,48,49,35,45,\n5,2020,2020,Oldham Athletic
18978,Bolivia,CDM,M. Flores,19,47,63,255958,"5'9""",150lbs,Right,...,57,32,43,48,44,49,\n2,2020,2020,Club Bolívar

In [22]:
fifa['Height']

0         5'7"
1         6'2"
2         6'2"
3        5'11"
4         5'9"
         ...
18974    5'10"
18975     5'7"
18976    5'10"
18977     5'9"
18978     5'9"
Name: Height, Length: 18979, dtype: object

In [23]:
# Function to convert height from feet and inches to centimeters
def height_to_cm(height):
    # Split the height string by the apostrophe
    feet, inches = height.split("'")
    
    # Remove the double quote and convert inches to integer
    inches = inches.replace("\"", "")
    
    # Convert to total inches and then to cm
    total_inches = int(feet) * 12 + int(inches)
    return total_inches * 2.54

# Apply the function to the 'Height' column and create a new 'Height_cm' column
fifa['Height_cm'] = fifa['Height'].apply(height_to_cm)

In [24]:
fifa['Height_cm']

0        170.18
1        187.96
2        187.96
3        180.34
4        175.26
          ...
18974    177.80
18975    170.18
18976    177.80
18977    175.26
18978    175.26
Name: Height_cm, Length: 18979, dtype: float64

In [25]:
# Function to convert height from feet and inches to centimeters
def height_to_cm(height):
    # Split the height string by the apostrophe
    feet, inches = height.split("'")
    
    # Remove the double quote and convert inches to integer
    inches = inches.replace("\"", "")
    
    # Convert to total inches and then to cm
    total_inches = int(feet) * 12 + int(inches)
    return total_inches * 2.54

# Apply the function to the 'Height' column, convert the result to int, and create a new 'Height_cm' column
fifa['Height_cm'] = fifa['Height'].apply(height_to_cm).round().astype(int)

In [26]:
fifa['Height_cm']

0        170
1        188
2        188
3        180
4        175
        ...
18974    178
18975    170
18976    178
18977    175
18978    175
Name: Height_cm, Length: 18979, dtype: int32

In [27]:
fifa

,Nationality,Positions,Name,Age,OVA,POT,ID,Height,Weight,foot,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract_start,Contract_end,Teams,Height_cm
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,"5'7""",159lbs,Left,...,92,91,95,38,65,\n372,2004,2004,FC Barcelona,170
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,"6'2""",183lbs,Right,...,93,81,89,35,77,\n344,2018,2018,Juventus,188
2,Slovenia,GK,J. Oblak,27,91,93,200389,"6'2""",192lbs,Right,...,92,78,90,52,90,\n86,2014,2014,Atlético Madrid,188
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,"5'11""",154lbs,Right,...,86,93,88,64,78,\n163,2015,2015,Manchester City,180
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,"5'9""",150lbs,Right,...,85,86,94,36,59,\n273,2017,2017,Paris Saint-Germain,175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,"5'10""",154lbs,Right,...,23,26,27,50,48,\n2,2020,2020,Chongqing Dangdai Lifan FC SWM Team,178
18975,England,ST,V. Da Silva,17,47,67,258736,"5'7""",128lbs,Right,...,46,40,53,16,40,\n3,2020,2020,Oldham Athletic,170
18976,China PR,CB,Xia Ao,21,47,55,247223,"5'10""",146lbs,Right,...,28,26,38,48,51,\n3,2018,2018,Wuhan Zall,178
18977,England,CM,B. Hough,17,47,67,258760,"5'9""",143lbs,Right,...,40,48,49,35,45,\n5,2020,2020,Oldham Athletic,175
18978,Bolivia,CDM,M. Flores,19,47,63,255958,"5'9""",150lbs,Right,...,32,43,48,44,49,\n2,2020,2020,Club Bolívar,175

In [28]:
fifa.drop(['Height'], inplace = True, axis = 1)

In [29]:
fifa

,Nationality,Positions,Name,Age,OVA,POT,ID,Weight,foot,BOV,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract_start,Contract_end,Teams,Height_cm
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,159lbs,Left,93,...,92,91,95,38,65,\n372,2004,2004,FC Barcelona,170
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,183lbs,Right,92,...,93,81,89,35,77,\n344,2018,2018,Juventus,188
2,Slovenia,GK,J. Oblak,27,91,93,200389,192lbs,Right,91,...,92,78,90,52,90,\n86,2014,2014,Atlético Madrid,188
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,154lbs,Right,91,...,86,93,88,64,78,\n163,2015,2015,Manchester City,180
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,150lbs,Right,91,...,85,86,94,36,59,\n273,2017,2017,Paris Saint-Germain,175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,154lbs,Right,49,...,23,26,27,50,48,\n2,2020,2020,Chongqing Dangdai Lifan FC SWM Team,178
18975,England,ST,V. Da Silva,17,47,67,258736,128lbs,Right,51,...,46,40,53,16,40,\n3,2020,2020,Oldham Athletic,170
18976,China PR,CB,Xia Ao,21,47,55,247223,146lbs,Right,49,...,28,26,38,48,51,\n3,2018,2018,Wuhan Zall,178
18977,England,CM,B. Hough,17,47,67,258760,143lbs,Right,51,...,40,48,49,35,45,\n5,2020,2020,Oldham Athletic,175
18978,Bolivia,CDM,M. Flores,19,47,63,255958,150lbs,Right,48,...,32,43,48,44,49,\n2,2020,2020,Club Bolívar,175

In [30]:
# Remove non-numeric characters and convert the 'weight' column to integers
fifa['Weight'] = fifa['Weight'].str.replace(r'[^0-9]', '', regex=True).astype(int)

In [31]:
fifa

,Nationality,Positions,Name,Age,OVA,POT,ID,Weight,foot,BOV,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract_start,Contract_end,Teams,Height_cm
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,159,Left,93,...,92,91,95,38,65,\n372,2004,2004,FC Barcelona,170
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,183,Right,92,...,93,81,89,35,77,\n344,2018,2018,Juventus,188
2,Slovenia,GK,J. Oblak,27,91,93,200389,192,Right,91,...,92,78,90,52,90,\n86,2014,2014,Atlético Madrid,188
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,154,Right,91,...,86,93,88,64,78,\n163,2015,2015,Manchester City,180
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,150,Right,91,...,85,86,94,36,59,\n273,2017,2017,Paris Saint-Germain,175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,154,Right,49,...,23,26,27,50,48,\n2,2020,2020,Chongqing Dangdai Lifan FC SWM Team,178
18975,England,ST,V. Da Silva,17,47,67,258736,128,Right,51,...,46,40,53,16,40,\n3,2020,2020,Oldham Athletic,170
18976,China PR,CB,Xia Ao,21,47,55,247223,146,Right,49,...,28,26,38,48,51,\n3,2018,2018,Wuhan Zall,178
18977,England,CM,B. Hough,17,47,67,258760,143,Right,51,...,40,48,49,35,45,\n5,2020,2020,Oldham Athletic,175
18978,Bolivia,CDM,M. Flores,19,47,63,255958,150,Right,48,...,32,43,48,44,49,\n2,2020,2020,Club Bolívar,175

In [32]:
fifa = fifa.rename({"Weight": "Weight_lbs"}, axis =1)

In [33]:
fifa

,Nationality,Positions,Name,Age,OVA,POT,ID,Weight_lbs,foot,BOV,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract_start,Contract_end,Teams,Height_cm
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,159,Left,93,...,92,91,95,38,65,\n372,2004,2004,FC Barcelona,170
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,183,Right,92,...,93,81,89,35,77,\n344,2018,2018,Juventus,188
2,Slovenia,GK,J. Oblak,27,91,93,200389,192,Right,91,...,92,78,90,52,90,\n86,2014,2014,Atlético Madrid,188
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,154,Right,91,...,86,93,88,64,78,\n163,2015,2015,Manchester City,180
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,150,Right,91,...,85,86,94,36,59,\n273,2017,2017,Paris Saint-Germain,175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,154,Right,49,...,23,26,27,50,48,\n2,2020,2020,Chongqing Dangdai Lifan FC SWM Team,178
18975,England,ST,V. Da Silva,17,47,67,258736,128,Right,51,...,46,40,53,16,40,\n3,2020,2020,Oldham Athletic,170
18976,China PR,CB,Xia Ao,21,47,55,247223,146,Right,49,...,28,26,38,48,51,\n3,2018,2018,Wuhan Zall,178
18977,England,CM,B. Hough,17,47,67,258760,143,Right,51,...,40,48,49,35,45,\n5,2020,2020,Oldham Athletic,175
18978,Bolivia,CDM,M. Flores,19,47,63,255958,150,Right,48,...,32,43,48,44,49,\n2,2020,2020,Club Bolívar,175

In [34]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 76 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Nationality       18979 non-null  object
 1   Positions         18979 non-null  object
 2   Name              18979 non-null  object
 3   Age               18979 non-null  int64
 4   OVA               18979 non-null  int64
 5   POT               18979 non-null  int64
 6   ID                18979 non-null  int64
 7   Weight_lbs        18979 non-null  int32
 8   foot              18979 non-null  object
 9   BOV               18979 non-null  int64
 10  BP                18979 non-null  object
 11  Growth            18979 non-null  int64
 12  Joined            18979 non-null  object
 13  Loan Date End     1013 non-null   object
 14  Value             18979 non-null  object
 15  Wage              18979 non-null  object
 16  Release Clause    18979 non-null  object
 17  Attacking         18979 non-null  int64
 18  Crossing          18979 non-null  int64
 19  Finishing         18979 non-null  int64
 20  Heading Accuracy  18979 non-null  int64
 21  Short Passing     18979 non-null  int64
 22  Volleys           18979 non-null  int64
 23  Skill             18979 non-null  int64
 24  Dribbling         18979 non-null  int64
 25  Curve             18979 non-null  int64
 26  FK Accuracy       18979 non-null  int64
 27  Long Passing      18979 non-null  int64
 28  Ball Control      18979 non-null  int64
 29  Movement          18979 non-null  int64
 30  Acceleration      18979 non-null  int64
 31  Sprint Speed      18979 non-null  int64
 32  Agility           18979 non-null  int64
 33  Reactions         18979 non-null  int64
 34  Balance           18979 non-null  int64
 35  Power             18979 non-null  int64
 36  Shot Power        18979 non-null  int64
 37  Jumping           18979 non-null  int64
 38  Stamina           18979 non-null  int64
 39  Strength          18979 non-null  int64
 40  Long Shots        18979 non-null  int64
 41  Mentality         18979 non-null  int64
 42  Aggression        18979 non-null  int64
 43  Interceptions     18979 non-null  int64
 44  Positioning       18979 non-null  int64
 45  Vision            18979 non-null  int64
 46  Penalties         18979 non-null  int64
 47  Composure         18979 non-null  int64
 48  Defending         18979 non-null  int64
 49  Marking           18979 non-null  int64
 50  Standing Tackle   18979 non-null  int64
 51  Sliding Tackle    18979 non-null  int64
 52  Goalkeeping       18979 non-null  int64
 53  GK Diving         18979 non-null  int64
 54  GK Handling       18979 non-null  int64
 55  GK Kicking        18979 non-null  int64
 56  GK Positioning    18979 non-null  int64
 57  GK Reflexes       18979 non-null  int64
 58  Total Stats       18979 non-null  int64
 59  Base Stats        18979 non-null  int64
 60  W/F               18979 non-null  object
 61  SM                18979 non-null  object
 62  A/W               18979 non-null  object
 63  D/W               18979 non-null  object
 64  IR                18979 non-null  object
 65  PAC               18979 non-null  int64
 66  SHO               18979 non-null  int64
 67  PAS               18979 non-null  int64
 68  DRI               18979 non-null  int64
 69  DEF               18979 non-null  int64
 70  PHY               18979 non-null  int64
 71  Hits              18979 non-null  object
 72  Contract_start    18979 non-null  int32
 73  Contract_end      18979 non-null  int32
 74  Teams             18979 non-null  object
 75  Height_cm         18979 non-null  int32
dtypes: int32(4), int64(55), object(17)
memory usage: 10.7+ MB

In [35]:
print(fifa['Loan Date End'])

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
18974    NaN
18975    NaN
18976    NaN
18977    NaN
18978    NaN
Name: Loan Date End, Length: 18979, dtype: object

In [36]:
fifa[['Value']]

        Value
0      €67.5M
1        €46M
2        €75M
3        €87M
4        €90M
...       ...
18974    €35K
18975    €60K
18976    €40K
18977    €60K
18978    €60K

[18979 rows x 1 columns]

In [37]:
## Convert Value to float

In [38]:
# Function to convert values
def convert_value(value):
    # Remove the euro symbol and treat M as (Million) and K as (Thousands)
    value = value.replace('€', '').strip()  # Use 'value' instead of 'Value'
    
    # Check for M (Millions) or K (Thousands)
    if 'M' in value:
        return float(value.replace('M', '')) * 1_000_000  # Convert millions to integers
    elif 'K' in value:
        return float(value.replace('K', '')) * 1_000  # Convert thousands to integers
    else:
        return float(value)  # In case there is no M or K, just convert directly to float

# Apply the cleaning
fifa['Value'] = fifa['Value'].apply(convert_value)

In [39]:
fifa[['Value']]

            Value
0      67500000.0
1      46000000.0
2      75000000.0
3      87000000.0
4      90000000.0
...           ...
18974     35000.0
18975     60000.0
18976     40000.0
18977     60000.0
18978     60000.0

[18979 rows x 1 columns]

In [40]:
# Function to convert wage values
def convert_wage(wage):
    # Remove the euro symbol and treat M as (Million) and K as (Thousands)
    wage = wage.replace('€', '').strip()  # Use 'wage' consistently
    
    # Check for M (Millions) or K (Thousands)
    if 'M' in wage:
        return float(wage.replace('M', '')) * 1_000_000  # Convert millions to integers
    elif 'K' in wage:
        return float(wage.replace('K', '')) * 1_000  # Convert thousands to integers
    else:
        return float(wage)  # In case there is no M or K, just convert directly to float

# Apply the cleaning to the 'Wage' column
fifa['Wage'] = fifa['Wage'].apply(convert_wage)

In [41]:
print(fifa['Wage'].head())

0    560000.0
1    220000.0
2    125000.0
3    370000.0
4    270000.0
Name: Wage, dtype: float64

In [42]:
print(fifa['Release Clause'].head())

0    €138.4M
1     €75.9M
2    €159.4M
3      €161M
4    €166.5M
Name: Release Clause, dtype: object

In [43]:
# Function to convert release clause values
def convert_release_clause(release_clause):
    # Remove the euro symbol and treat M as (Million) and K as (Thousands)
    release_clause = release_clause.replace('€', '').strip()  # Remove '€' symbol and strip any leading/trailing spaces
    
    # Check for M (Millions) or K (Thousands)
    if 'M' in release_clause:
        return float(release_clause.replace('M', '')) * 1_000_000  # Convert millions to integers
    elif 'K' in release_clause:
        return float(release_clause.replace('K', '')) * 1_000  # Convert thousands to integers
    else:
        return float(release_clause)  # In case there is no M or K, just convert directly to float

# Apply the cleaning function to the 'Release Clause' column
fifa['Release Clause'] = fifa['Release Clause'].apply(convert_release_clause)

In [44]:
print(fifa['Release Clause'].head())

0    138400000.0
1     75900000.0
2    159400000.0
3    161000000.0
4    166500000.0
Name: Release Clause, dtype: float64

In [45]:
print(fifa['W/F'].head())

0    4 ★
1    4 ★
2    3 ★
3    5 ★
4    5 ★
Name: W/F, dtype: object

In [46]:
print(fifa['W/F'].unique())

['4 ★' '3 ★' '5 ★' '2 ★' '1 ★']

In [47]:
# Removing ★ character
fifa['W/F'] = fifa['W/F'].replace({r'★': ''}, regex=True)
# Convert to int
fifa['W/F'] = fifa['W/F'].astype(int)

In [48]:
print(fifa['W/F'].head())

0    4
1    4
2    3
3    5
4    5
Name: W/F, dtype: int32

In [49]:
print(fifa['SM'].head())

0    4★
1    5★
2    1★
3    4★
4    5★
Name: SM, dtype: object

In [50]:
# Removing ★ character
fifa['SM'] = fifa['SM'].replace({r'★': ''}, regex=True)
# Convert to int
fifa['SM'] = fifa['SM'].astype(int)

In [51]:
print(fifa['SM'].head())

0    4
1    5
2    1
3    4
4    5
Name: SM, dtype: int32

In [52]:
print(fifa['IR'].head())

0    5 ★
1    5 ★
2    3 ★
3    4 ★
4    5 ★
Name: IR, dtype: object

In [53]:
# Removing ★ character
fifa['IR'] = fifa['IR'].replace({r'★': ''}, regex=True)
# Convert to int
fifa['IR'] = fifa['IR'].astype(int)

In [54]:
print(fifa['IR'].head())

0    5
1    5
2    3
3    4
4    5
Name: IR, dtype: int32

In [55]:
print(fifa['Hits'].head())

0    \n372
1    \n344
2     \n86
3    \n163
4    \n273
Name: Hits, dtype: object

In [56]:
# Removing spaces and new line
fifa['Hits'] = fifa['Hits'].replace({r'\n': '', r'\s+': ''}, regex=True)
# Treat 'K' as 1000 and 'M' as 1000000, # Multiplying by 1000 and 1000000 for 'K' and 'M'
fifa['Hits'] = fifa['Hits'].replace({r'K': '*1000', r'M': '*1000000'}, regex=True)
# Clean the 'Hits' column by evaluating any mathematical expressions (like '1.3*1000')
fifa['Hits'] = fifa['Hits'].map(pd.eval).astype(int)

In [57]:
print(fifa['Hits'])

0        372
1        344
2         86
3        163
4        273
        ...
18974      2
18975      3
18976      3
18977      5
18978      2
Name: Hits, Length: 18979, dtype: int32

In [58]:
fifa

,Nationality,Positions,Name,Age,OVA,POT,ID,Weight_lbs,foot,BOV,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract_start,Contract_end,Teams,Height_cm
0,Argentina,RW ST CF,L. Messi,33,93,93,158023,159,Left,93,...,92,91,95,38,65,372,2004,2004,FC Barcelona,170
1,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,183,Right,92,...,93,81,89,35,77,344,2018,2018,Juventus,188
2,Slovenia,GK,J. Oblak,27,91,93,200389,192,Right,91,...,92,78,90,52,90,86,2014,2014,Atlético Madrid,188
3,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,154,Right,91,...,86,93,88,64,78,163,2015,2015,Manchester City,180
4,Brazil,LW CAM,Neymar Jr,28,91,91,190871,150,Right,91,...,85,86,94,36,59,273,2017,2017,Paris Saint-Germain,175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,China PR,CB,Zhang Mengxuan,21,47,52,257710,154,Right,49,...,23,26,27,50,48,2,2020,2020,Chongqing Dangdai Lifan FC SWM Team,178
18975,England,ST,V. Da Silva,17,47,67,258736,128,Right,51,...,46,40,53,16,40,3,2020,2020,Oldham Athletic,170
18976,China PR,CB,Xia Ao,21,47,55,247223,146,Right,49,...,28,26,38,48,51,3,2018,2018,Wuhan Zall,178
18977,England,CM,B. Hough,17,47,67,258760,143,Right,51,...,40,48,49,35,45,5,2020,2020,Oldham Athletic,175
18978,Bolivia,CDM,M. Flores,19,47,63,255958,150,Right,48,...,32,43,48,44,49,2,2020,2020,Club Bolívar,175

In [59]:
fifa.columns

Index(['Nationality', 'Positions', 'Name', 'Age', 'OVA', 'POT', 'ID',
       'Weight_lbs', 'foot', 'BOV', 'BP', 'Growth', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits', 'Contract_start', 'Contract_end', 'Teams',
       'Height_cm'],
      dtype='object')

In [60]:
fifa.drop(['Nationality','Name','Positions','BP','ID','foot','Sprint Speed','Reactions','Composure','GK Handling','GK Kicking','GK Positioning','Base Stats','W/F', 'SM', 'A/W', 'D/W','IR'],inplace = True, axis = 1)

In [61]:
fifa.columns

Index(['Age', 'OVA', 'POT', 'Weight_lbs', 'BOV', 'Growth', 'Joined',
       'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Attacking',
       'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Agility', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Reflexes',
       'Total Stats', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits',
       'Contract_start', 'Contract_end', 'Teams', 'Height_cm'],
      dtype='object')

In [62]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 58 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               18979 non-null  int64
 1   OVA               18979 non-null  int64
 2   POT               18979 non-null  int64
 3   Weight_lbs        18979 non-null  int32
 4   BOV               18979 non-null  int64
 5   Growth            18979 non-null  int64
 6   Joined            18979 non-null  object
 7   Loan Date End     1013 non-null   object
 8   Value             18979 non-null  float64
 9   Wage              18979 non-null  float64
 10  Release Clause    18979 non-null  float64
 11  Attacking         18979 non-null  int64
 12  Crossing          18979 non-null  int64
 13  Finishing         18979 non-null  int64
 14  Heading Accuracy  18979 non-null  int64
 15  Short Passing     18979 non-null  int64
 16  Volleys           18979 non-null  int64
 17  Skill             18979 non-null  int64
 18  Dribbling         18979 non-null  int64
 19  Curve             18979 non-null  int64
 20  FK Accuracy       18979 non-null  int64
 21  Long Passing      18979 non-null  int64
 22  Ball Control      18979 non-null  int64
 23  Movement          18979 non-null  int64
 24  Acceleration      18979 non-null  int64
 25  Agility           18979 non-null  int64
 26  Balance           18979 non-null  int64
 27  Power             18979 non-null  int64
 28  Shot Power        18979 non-null  int64
 29  Jumping           18979 non-null  int64
 30  Stamina           18979 non-null  int64
 31  Strength          18979 non-null  int64
 32  Long Shots        18979 non-null  int64
 33  Mentality         18979 non-null  int64
 34  Aggression        18979 non-null  int64
 35  Interceptions     18979 non-null  int64
 36  Positioning       18979 non-null  int64
 37  Vision            18979 non-null  int64
 38  Penalties         18979 non-null  int64
 39  Defending         18979 non-null  int64
 40  Marking           18979 non-null  int64
 41  Standing Tackle   18979 non-null  int64
 42  Sliding Tackle    18979 non-null  int64
 43  Goalkeeping       18979 non-null  int64
 44  GK Diving         18979 non-null  int64
 45  GK Reflexes       18979 non-null  int64
 46  Total Stats       18979 non-null  int64
 47  PAC               18979 non-null  int64
 48  SHO               18979 non-null  int64
 49  PAS               18979 non-null  int64
 50  DRI               18979 non-null  int64
 51  DEF               18979 non-null  int64
 52  PHY               18979 non-null  int64
 53  Hits              18979 non-null  int32
 54  Contract_start    18979 non-null  int32
 55  Contract_end      18979 non-null  int32
 56  Teams             18979 non-null  object
 57  Height_cm         18979 non-null  int32
dtypes: float64(3), int32(5), int64(47), object(3)
memory usage: 8.0+ MB

In [63]:
print(fifa['Joined'])

0         Jul 1, 2004
1        Jul 10, 2018
2        Jul 16, 2014
3        Aug 30, 2015
4         Aug 3, 2017
             ...
18974     Aug 1, 2020
18975     Aug 1, 2020
18976    Jul 13, 2018
18977     Aug 1, 2020
18978     Jan 1, 2020
Name: Joined, Length: 18979, dtype: object

In [64]:
print(fifa['Joined'])

0         Jul 1, 2004
1        Jul 10, 2018
2        Jul 16, 2014
3        Aug 30, 2015
4         Aug 3, 2017
             ...
18974     Aug 1, 2020
18975     Aug 1, 2020
18976    Jul 13, 2018
18977     Aug 1, 2020
18978     Jan 1, 2020
Name: Joined, Length: 18979, dtype: object

In [65]:
import pandas as pd

# Sample dataframe with a date column
df = pd.DataFrame({
    'Date': ['Jul 1, 2004', 'Jul 10, 2018', 'Jul 16, 2014'],
    'Feature1': [0.5, 0.2, -0.3],
    'Feature2': [1.0, 0.8, 0.3]
})

# Convert the 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Extract relevant features (for example, the year, month, and day)
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

In [66]:
# Now, drop the original 'Date' column if not needed
df = df.drop(columns=['Date'])

print(df)

   Feature1  Feature2  Year  Month  Day
0       0.5       1.0  2004      7    1
1       0.2       0.8  2018      7   10
2      -0.3       0.3  2014      7   16

In [67]:
df = pd.get_dummies(df, drop_first=True)  # One-hot encoding for categorical columns

In [68]:
fifa

,Age,OVA,POT,Weight_lbs,BOV,Growth,Joined,Loan Date End,Value,Wage,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract_start,Contract_end,Teams,Height_cm
0,33,93,93,159,93,0,"Jul 1, 2004",NaN,67500000.0,560000.0,...,92,91,95,38,65,372,2004,2004,FC Barcelona,170
1,35,92,92,183,92,0,"Jul 10, 2018",NaN,46000000.0,220000.0,...,93,81,89,35,77,344,2018,2018,Juventus,188
2,27,91,93,192,91,2,"Jul 16, 2014",NaN,75000000.0,125000.0,...,92,78,90,52,90,86,2014,2014,Atlético Madrid,188
3,29,91,91,154,91,0,"Aug 30, 2015",NaN,87000000.0,370000.0,...,86,93,88,64,78,163,2015,2015,Manchester City,180
4,28,91,91,150,91,0,"Aug 3, 2017",NaN,90000000.0,270000.0,...,85,86,94,36,59,273,2017,2017,Paris Saint-Germain,175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,21,47,52,154,49,5,"Aug 1, 2020",NaN,35000.0,1000.0,...,23,26,27,50,48,2,2020,2020,Chongqing Dangdai Lifan FC SWM Team,178
18975,17,47,67,128,51,20,"Aug 1, 2020",NaN,60000.0,500.0,...,46,40,53,16,40,3,2020,2020,Oldham Athletic,170
18976,21,47,55,146,49,8,"Jul 13, 2018",NaN,40000.0,1000.0,...,28,26,38,48,51,3,2018,2018,Wuhan Zall,178
18977,17,47,67,143,51,20,"Aug 1, 2020",NaN,60000.0,500.0,...,40,48,49,35,45,5,2020,2020,Oldham Athletic,175
18978,19,47,63,150,48,16,"Jan 1, 2020",NaN,60000.0,500.0,...,32,43,48,44,49,2,2020,2020,Club Bolívar,175

In [69]:
print(fifa['Teams'])

0                               FC Barcelona
1                                   Juventus
2                            Atlético Madrid
3                            Manchester City
4                        Paris Saint-Germain
                        ...
18974    Chongqing Dangdai Lifan FC SWM Team
18975                        Oldham Athletic
18976                             Wuhan Zall
18977                        Oldham Athletic
18978                           Club Bolívar
Name: Teams, Length: 18979, dtype: object

In [70]:
Team1 = {'Teams': ['FC Barcelona', 'Juventus', 'Atlético Madrid', 'Manchester City', 'Paris Saint-Germain']}

df = pd.DataFrame(fifa)  # This defines the DataFrame with the 'Teams' column

In [71]:
import pandas as pd

Team1 = {'Teams': ['FC Barcelona', 'Juventus', 'Atlético Madrid', 'Manchester City', 'Paris Saint-Germain']}

df = pd.DataFrame(fifa)

In [72]:
# Label encode the 'Teams' column by assigning a unique integer to each unique team
fifa['Teams'] = pd.factorize(df['Teams'])[0]

# Check the result
print(df[['Teams']].head(5))

                 Teams
0         FC Barcelona
1             Juventus
2      Atlético Madrid
3      Manchester City
4  Paris Saint-Germain

In [73]:
# Example DataFrame with team names
Team1 = {'Teams': ['FC Barcelona', 'Juventus', 'Atlético Madrid', 'Manchester City', 'Paris Saint-Germain']}
df = pd.DataFrame(fifa)

# Use factorize on the 'Teams' column
df['Teams'] = pd.factorize(df['Teams'])[0]

In [74]:
print(df[['Teams']].head(5))

   Teams
0      0
1      1
2      2
3      3
4      4

In [75]:
Team1 = {'Teams': ['FC Barcelona', 'Juventus', 'Atlético Madrid', 'Manchester City', 'Paris Saint-Germain']}
df = pd.DataFrame(fifa)

# Use factorize on the 'Teams' column to convert team names to integer labels
df['Teams'] = pd.factorize(df['Teams'])[0]

In [76]:
# Convert teams column to int
df['Teams'] = df['Teams'].astype(int)

In [77]:
print(df[['Teams']].head(5))

   Teams
0      0
1      1
2      2
3      3
4      4

In [78]:
print(df['Teams'].dtype)

int32

In [79]:
print(fifa['Loan Date End'])

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
18974    NaN
18975    NaN
18976    NaN
18977    NaN
18978    NaN
Name: Loan Date End, Length: 18979, dtype: object

In [80]:
fifa['Loan Date End']=fifa['Loan Date End'].fillna('Not Available')

In [81]:
fifa

,Age,OVA,POT,Weight_lbs,BOV,Growth,Joined,Loan Date End,Value,Wage,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract_start,Contract_end,Teams,Height_cm
0,33,93,93,159,93,0,"Jul 1, 2004",Not Available,67500000.0,560000.0,...,92,91,95,38,65,372,2004,2004,0,170
1,35,92,92,183,92,0,"Jul 10, 2018",Not Available,46000000.0,220000.0,...,93,81,89,35,77,344,2018,2018,1,188
2,27,91,93,192,91,2,"Jul 16, 2014",Not Available,75000000.0,125000.0,...,92,78,90,52,90,86,2014,2014,2,188
3,29,91,91,154,91,0,"Aug 30, 2015",Not Available,87000000.0,370000.0,...,86,93,88,64,78,163,2015,2015,3,180
4,28,91,91,150,91,0,"Aug 3, 2017",Not Available,90000000.0,270000.0,...,85,86,94,36,59,273,2017,2017,4,175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,21,47,52,154,49,5,"Aug 1, 2020",Not Available,35000.0,1000.0,...,23,26,27,50,48,2,2020,2020,196,178
18975,17,47,67,128,51,20,"Aug 1, 2020",Not Available,60000.0,500.0,...,46,40,53,16,40,3,2020,2020,649,170
18976,21,47,55,146,49,8,"Jul 13, 2018",Not Available,40000.0,1000.0,...,28,26,38,48,51,3,2018,2018,152,178
18977,17,47,67,143,51,20,"Aug 1, 2020",Not Available,60000.0,500.0,...,40,48,49,35,45,5,2020,2020,649,175
18978,19,47,63,150,48,16,"Jan 1, 2020",Not Available,60000.0,500.0,...,32,43,48,44,49,2,2020,2020,505,175

In [82]:
print(fifa['Loan Date End'])

0        Not Available
1        Not Available
2        Not Available
3        Not Available
4        Not Available
             ...
18974    Not Available
18975    Not Available
18976    Not Available
18977    Not Available
18978    Not Available
Name: Loan Date End, Length: 18979, dtype: object

In [83]:
fifa

,Age,OVA,POT,Weight_lbs,BOV,Growth,Joined,Loan Date End,Value,Wage,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract_start,Contract_end,Teams,Height_cm
0,33,93,93,159,93,0,"Jul 1, 2004",Not Available,67500000.0,560000.0,...,92,91,95,38,65,372,2004,2004,0,170
1,35,92,92,183,92,0,"Jul 10, 2018",Not Available,46000000.0,220000.0,...,93,81,89,35,77,344,2018,2018,1,188
2,27,91,93,192,91,2,"Jul 16, 2014",Not Available,75000000.0,125000.0,...,92,78,90,52,90,86,2014,2014,2,188
3,29,91,91,154,91,0,"Aug 30, 2015",Not Available,87000000.0,370000.0,...,86,93,88,64,78,163,2015,2015,3,180
4,28,91,91,150,91,0,"Aug 3, 2017",Not Available,90000000.0,270000.0,...,85,86,94,36,59,273,2017,2017,4,175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,21,47,52,154,49,5,"Aug 1, 2020",Not Available,35000.0,1000.0,...,23,26,27,50,48,2,2020,2020,196,178
18975,17,47,67,128,51,20,"Aug 1, 2020",Not Available,60000.0,500.0,...,46,40,53,16,40,3,2020,2020,649,170
18976,21,47,55,146,49,8,"Jul 13, 2018",Not Available,40000.0,1000.0,...,28,26,38,48,51,3,2018,2018,152,178
18977,17,47,67,143,51,20,"Aug 1, 2020",Not Available,60000.0,500.0,...,40,48,49,35,45,5,2020,2020,649,175
18978,19,47,63,150,48,16,"Jan 1, 2020",Not Available,60000.0,500.0,...,32,43,48,44,49,2,2020,2020,505,175

In [84]:
fifa.drop(['Loan Date End'], inplace = True, axis = 1)

In [85]:
fifa

,Age,OVA,POT,Weight_lbs,BOV,Growth,Joined,Value,Wage,Release Clause,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract_start,Contract_end,Teams,Height_cm
0,33,93,93,159,93,0,"Jul 1, 2004",67500000.0,560000.0,138400000.0,...,92,91,95,38,65,372,2004,2004,0,170
1,35,92,92,183,92,0,"Jul 10, 2018",46000000.0,220000.0,75900000.0,...,93,81,89,35,77,344,2018,2018,1,188
2,27,91,93,192,91,2,"Jul 16, 2014",75000000.0,125000.0,159400000.0,...,92,78,90,52,90,86,2014,2014,2,188
3,29,91,91,154,91,0,"Aug 30, 2015",87000000.0,370000.0,161000000.0,...,86,93,88,64,78,163,2015,2015,3,180
4,28,91,91,150,91,0,"Aug 3, 2017",90000000.0,270000.0,166500000.0,...,85,86,94,36,59,273,2017,2017,4,175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,21,47,52,154,49,5,"Aug 1, 2020",35000.0,1000.0,57000.0,...,23,26,27,50,48,2,2020,2020,196,178
18975,17,47,67,128,51,20,"Aug 1, 2020",60000.0,500.0,165000.0,...,46,40,53,16,40,3,2020,2020,649,170
18976,21,47,55,146,49,8,"Jul 13, 2018",40000.0,1000.0,70000.0,...,28,26,38,48,51,3,2018,2018,152,178
18977,17,47,67,143,51,20,"Aug 1, 2020",60000.0,500.0,165000.0,...,40,48,49,35,45,5,2020,2020,649,175
18978,19,47,63,150,48,16,"Jan 1, 2020",60000.0,500.0,167000.0,...,32,43,48,44,49,2,2020,2020,505,175

In [86]:
fifa.columns

Index(['Age', 'OVA', 'POT', 'Weight_lbs', 'BOV', 'Growth', 'Joined', 'Value',
       'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Agility', 'Balance', 'Power', 'Shot Power', 'Jumping',
       'Stamina', 'Strength', 'Long Shots', 'Mentality', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Reflexes', 'Total Stats', 'PAC', 'SHO', 'PAS', 'DRI',
       'DEF', 'PHY', 'Hits', 'Contract_start', 'Contract_end', 'Teams',
       'Height_cm'],
      dtype='object')

In [87]:
from sklearn.preprocessing import StandardScaler
import numpy as np

sc=StandardScaler()
fifa['Value']=sc.fit_transform(np.array(fifa['Value']).reshape(-1,1))

In [88]:
fifa

,Age,OVA,POT,Weight_lbs,BOV,Growth,Joined,Value,Wage,Release Clause,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract_start,Contract_end,Teams,Height_cm
0,33,93,93,159,93,0,"Jul 1, 2004",12.804571,560000.0,138400000.0,...,92,91,95,38,65,372,2004,2004,0,170
1,35,92,92,183,92,0,"Jul 10, 2018",8.586801,220000.0,75900000.0,...,93,81,89,35,77,344,2018,2018,1,188
2,27,91,93,192,91,2,"Jul 16, 2014",14.275886,125000.0,159400000.0,...,92,78,90,52,90,86,2014,2014,2,188
3,29,91,91,154,91,0,"Aug 30, 2015",16.629991,370000.0,161000000.0,...,86,93,88,64,78,163,2015,2015,3,180
4,28,91,91,150,91,0,"Aug 3, 2017",17.218517,270000.0,166500000.0,...,85,86,94,36,59,273,2017,2017,4,175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,21,47,52,154,49,5,"Aug 1, 2020",-0.430400,1000.0,57000.0,...,23,26,27,50,48,2,2020,2020,196,178
18975,17,47,67,128,51,20,"Aug 1, 2020",-0.425495,500.0,165000.0,...,46,40,53,16,40,3,2020,2020,649,170
18976,21,47,55,146,49,8,"Jul 13, 2018",-0.429419,1000.0,70000.0,...,28,26,38,48,51,3,2018,2018,152,178
18977,17,47,67,143,51,20,"Aug 1, 2020",-0.425495,500.0,165000.0,...,40,48,49,35,45,5,2020,2020,649,175
18978,19,47,63,150,48,16,"Jan 1, 2020",-0.425495,500.0,167000.0,...,32,43,48,44,49,2,2020,2020,505,175

In [89]:
X_train = fifa[['Age', 'Weight_lbs', 'BOV', 'Growth', 'Joined', 'Release Clause', 'Attacking', 'Crossing', 'Finishing','Heading Accuracy', 
        'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Agility', 'Balance', 'Power', 'Shot Power', 'Jumping',
       'Stamina', 'Strength', 'Long Shots', 'Mentality', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Reflexes', 'Total Stats', 'PAC', 'SHO', 'PAS', 'DRI',
       'DEF', 'PHY', 'Hits', 'Contract_start', 'Contract_end', 'Teams',
       'Height_cm']]

y_train = fifa['Value']

In [90]:
from sklearn.model_selection import train_test_split

# Define 'X' as the features (input variables), excluding the target column 'Value'
X = fifa.drop(columns=['Value'])

# Define 'y' as the target variable (what you're trying to predict)
y = fifa['Value']

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=30)

In [91]:
np.array(y_test)

array([ 0.50437603, -0.2214728 , -0.39803063, ..., -0.36860432,
        0.93596182, -0.28032541])

In [92]:
X_test

,Age,OVA,POT,Weight_lbs,BOV,Growth,Joined,Wage,Release Clause,Attacking,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract_start,Contract_end,Teams,Height_cm
3478,22,72,81,148,74,9,"Aug 17, 2019",6000.0,11000000.0,320,...,69,72,76,52,60,20,2019,2019,355,175
5782,27,69,71,170,71,2,"Aug 1, 2020",7000.0,2000000.0,273,...,41,58,50,70,72,6,2020,2020,274,180
16115,23,59,66,212,61,7,"Apr 11, 2017",2000.0,330000.0,167,...,20,30,35,57,77,6,2017,2017,460,196
18894,26,49,52,159,51,3,"Feb 28, 2015",1000.0,57000.0,215,...,40,51,49,34,46,1,2015,2015,177,178
12579,24,63,66,172,64,3,"Jan 12, 2019",650.0,563000.0,227,...,43,52,61,59,73,2,2019,2019,687,185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1152,28,77,77,176,77,0,"Jan 12, 2016",42000.0,17100000.0,354,...,73,79,73,62,75,29,2016,2016,37,183
18128,18,53,67,174,56,14,"Jan 1, 2020",500.0,234000.0,196,...,34,45,51,51,60,3,2020,2020,270,188
13817,26,62,66,154,64,4,"Jul 2, 2019",3000.0,639000.0,184,...,31,35,37,62,70,2,2019,2019,654,178
2386,25,74,78,152,76,4,"Aug 30, 2018",15000.0,10300000.0,331,...,71,75,74,64,65,29,2018,2018,76,178
7828,28,67,67,168,67,0,"May 6, 2020",6000.0,1300000.0,322,...,66,62,67,32,70,6,2020,2020,373,178

In [93]:
y_test

3478     0.504376
5782    -0.221473
16115   -0.398031
18894   -0.430400
12579   -0.353891
           ...
1152     1.328313
18128   -0.415686
13817   -0.368604
2386     0.935962
7828    -0.280325
Name: Value, Length: 3796, dtype: float64

In [94]:
y_train

10031   -0.314656
16513   -0.388222
15725   -0.399992
17698   -0.407839
753      1.916839
           ...
500      1.132137
12077   -0.344082
15277   -0.373509
4517     0.112025
5925    -0.182238
Name: Value, Length: 15183, dtype: float64

In [96]:
import pandas as pd

# Sample data with date strings
data = {'Date': ['Jul 5, 2018', 'Feb 15, 2017', 'Sep 22, 2015'],
        'Feature1': [0.5, 0.2, -0.3],
        'Feature2': [1.0, 0.8, 0.3]}

df = pd.DataFrame(data)

# Convert the 'Date' column to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Extract year, month, and day as numeric features
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Day'] = df['Date'].dt.day

# Now, you can drop the original 'Date' column if it's no longer needed
df = df.drop(columns=['Date'])

# Show the resulting dataframe
print(df)

   Feature1  Feature2  Year  Month  Day
0       0.5       1.0  2018      7    5
1       0.2       0.8  2017      2   15
2      -0.3       0.3  2015      9   22

In [98]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

# Train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
computer_prediction = model.predict(X_test)

# For regression, use mean squared error
mse = mean_squared_error(y_test, computer_prediction)
print(f'Mean Squared Error: {mse}')

# If you are doing classification, accuracy_score can be used:
# accuracy = accuracy_score(y_test, computer_prediction)
# print(f'Accuracy: {accuracy}')

ValueError: could not convert string to float: 'Jul 5, 2018'

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

# Initialize your model
model = LinearRegression()

# Perform cross-validation with Linear Regression
cv_scores = cross_val_score(model, X, y, cv=5, scoring='neg_mean_squared_error')

# Print average cross-validation score (mean MSE)
print(f'Average Cross-Validation MSE: {-cv_scores.mean()}')